services:
  library_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    ports:
      - "5431:5432" 
    volumes:
      - workouts_data:/var/lib/postgresql/data

volumes:
  workouts_data: